### ISSUE TITLE
example does not work responding {"message":"Token cannot be null or empty","error":"INVALID_TOKEN","timestamp":1656058235313}

### ISSUE THREAD

**Issue by raceychan** [conductor-sdk/conductor-python#95]
as the title suggests,
the simple_woker.py example in the README.md does not work

**Comment by gardusig** [comment]
Hey @raceychan, if you're using it with a Conductor Server that has authentication (e.g. [Orkes Playground](https://play.orkes.io/)), you might need to override the `AuthenticationSettings`, adding your actual keys. Otherwise, just ignore the `AuthenticationSettings` parameter :)

You can check out more details here: https://orkes.io/content/docs/getting-started/concepts/access-control

**Comment by raceychan** [comment]
> Hey @raceychan, if you're using it with a Conductor Server that has authentication (e.g. [Orkes Playground](https://play.orkes.io/)), you might need to override the `AuthenticationSettings`, adding your actual keys. Otherwise, just ignore the `AuthenticationSettings` parameter :)
> 
> You can check out more details here: https://orkes.io/content/docs/getting-started/concepts/access-control

thanks for the reply, about to check that out

**Comment by gardusig** [comment]
Closing this issue since there weren't new errors so far. Please reopen it if needed.
